"""Abstract interfaces (Protocols) that decouple core business logic from concrete AWS/SaaS implementations. All concrete adapters live in subdirectories; the core never imports from them."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from relay.config.schema import RelayConfig
from relay.core.model import Contact, Incident, Stream, TimelineEvent


@dataclass
class AICompletion:
    """The structured result of a single AI completion.

    Carries the generated ``text`` plus provenance/usage so callers can log
    cost and surface which provider/model produced a draft (docs/AI.md §5
    cost-control + labeling). ``text`` is None when the model declined or
    returned nothing; usage fields are best-effort (None when a provider does
    not report them).
    """

    text: str | None
    model: str = ""
    provider: str = ""
    input_tokens: int | None = None
    output_tokens: int | None = None


@runtime_checkable
class AlertSource(Protocol):
    """Protocol for inbound alert parsing."""

    def parse_event(self, raw_event: dict[str, Any]) -> Incident:
        """Parse a raw inbound event (e.g., EventBridge envelope) into the neutral Incident model.

        Raise ValueError for unrecognized events.
        """
        ...


@runtime_checkable
class Notifier(Protocol):
    """Protocol for outbound paging/notification."""

    def send(self, *, incident: Incident, contact_ids: list[str], stream: Stream) -> None:
        """Send a page (SMS/email) to the given contacts for the given incident.

        Raise on unrecoverable failure.
        """
        ...


@runtime_checkable
class IncidentSink(Protocol):
    """Protocol for writing incident records to external ticketing systems."""

    def create_incident(self, incident: Incident) -> str:
        """Create an external incident record (ServiceNow/GitLab).

        Return the external ticket/issue ID.
        """
        ...

    def update_incident(self, external_id: str, incident: Incident) -> None:
        """Update an existing external record — severity, state, timeline."""
        ...

    def close_incident(self, external_id: str, incident: Incident) -> None:
        """Mark the external record resolved/closed."""
        ...


@runtime_checkable
class Transport(Protocol):
    """Protocol for cross-account incident event routing."""

    def emit(self, *, incident: Incident, stream: Stream) -> None:
        """Publish an incident event to the cross-account central bus.

        Raise on delivery failure.
        """
        ...

    def emit_heartbeat(
        self,
        *,
        account_id: str,
        app_name: str,
        timestamp: str,
        environment: str = "unrouted",
        deployment_id: str | None = None,
        service_path: list[str] | None = None,
        org_path: list[dict[str, Any]] | None = None,
    ) -> None:
        """Publish a liveness heartbeat for this node to the central bus.

        ``org_path`` carries the node's org ancestry (root→leaf) so the Hub can
        rebuild the catalog/hierarchy from registrations alone. Best-effort:
        implementations log and return on failure rather than raising, so a
        heartbeat problem never disrupts the node.
        """
        ...


@runtime_checkable
class AIAssistant(Protocol):
    """Protocol for AI augmentation (briefing, investigation, AAR drafting).

    Implementations:
    - BedrockAssistant: single-shot calls to a Bedrock-hosted model (keeps data in AWS).
    - ClaudeCodeAssistant: subprocess agent loop with Relay skills (future, multi-step).
    - NoOpAIAssistant: returns None so callers fall back to deterministic output.

    All methods must degrade gracefully — return None on any failure, never raise.
    Output is always a draft, always labeled AI-generated by the caller.
    """

    def complete(
        self, *, system: str, prompt: str, max_tokens: int = 1024
    ) -> AICompletion | None:
        """Run a single-shot completion.

        Returns an :class:`AICompletion` (whose ``.text`` may itself be None if
        the model returned nothing), or None on any failure. Implementations
        must never raise — failure means deterministic fallback upstream.
        """
        ...


@runtime_checkable
class Forwarder(Protocol):
    """Protocol for forwarding selected incidents from a local-federated Hub to a central Hub.

    Implementations:
    - EventBridgeForwarder: publishes to a central EventBridge bus (used when scope=local-federated).
    - NoOpForwarder: does nothing (used when scope=local or scope=central).
    """

    def forward(self, incident: Incident) -> bool:
        """Forward an incident to the central Hub.

        Returns True on success, False if forwarding was skipped or failed gracefully.
        """
        ...


@runtime_checkable
class ContactStore(Protocol):
    """Protocol for contact PII storage."""

    def get_contact(self, contact_id: str) -> Contact | None:
        """Fetch contact PII by opaque ID.

        Returns None if not found.
        """
        ...

    def put_contact(self, contact: Contact) -> None:
        """Create or update a contact record."""
        ...

    def delete_contact(self, contact_id: str) -> None:
        """Hard-delete a contact and its PII."""
        ...


@runtime_checkable
class IncidentStore(Protocol):
    """Protocol for live incident state persistence."""

    def get_incident(self, correlation_id: str) -> Incident | None:
        """Fetch a live incident by correlation ID.

        Returns None if not found.
        """
        ...

    def put_incident(self, incident: Incident) -> None:
        """Upsert a live incident record."""
        ...

    def append_timeline_event(self, correlation_id: str, event: TimelineEvent) -> None:
        """Atomically append a timeline event.

        Prefer this over re-writing the whole incident when only adding events.
        """
        ...

    def list_open_incidents(self, account_id: str | None = None) -> list[Incident]:
        """List all non-closed incidents, optionally filtered by account."""
        ...

    def list_incidents(self, account_id: str | None = None) -> list[Incident]:
        """List ALL incidents (open + terminal), optionally filtered by account.

        Backs the history view and metrics rollups; callers slice or aggregate
        the full set themselves.
        """
        ...


@runtime_checkable
class ConfigStore(Protocol):
    """Protocol for relay configuration loading."""

    def get(self) -> RelayConfig:
        """Return the current in-memory config, loading from source if needed."""
        ...

    def refresh(self) -> RelayConfig:
        """Force a reload from the config source (GitLab)."""
        ...
